<?php
class MarketplaceController {
    public static function addToCart(): void {
        require_method('POST');
        $userId     = AuthMiddleware::requireAuth();
        $data       = json_decode($_POST['data'] ?? '', true) ?? null;
        $chatbotId  = InputSanitizer::positiveInt($data['chatbot_id'] ?? 0);
        $orderWeeks = InputSanitizer::positiveInt($data['order_weeks'] ?? 0) ?: null;

        if (!$data || !$chatbotId) {
            JsonResponse::error('Eksik parametreler!', 400, AppConfig::ERR_VALIDATION);
        }

        $db          = Database::getInstance();
        $sellerCheck = $db->selectSingle(
            "pms.status FROM param_marketplace_sellers pms
             JOIN chatbotlar c ON c.author_user_id = pms.user_id
             WHERE c.id = ? AND c.is_independent = 0",
            [$chatbotId]
        );
        if (!$sellerCheck || ($sellerCheck['status'] ?? '') !== 'active') {
            JsonResponse::error('Bu chatbot şu anda satışa kapalı. Satıcısı henüz pazaryeri kaydını tamamlamamış.', 422, AppConfig::ERR_SELLER_INACTIVE);
        }

        try {
            $id = $db->insert('user_cart', ['user_id' => $userId, 'chatbot_id' => $chatbotId, 'order_weeks' => $orderWeeks]);
            JsonResponse::success(['message' => 'Ürün sepete eklendi', 'id' => $id]);
        } catch (Exception $e) {
            $msg = str_contains($e->getMessage(), 'Duplicate entry')
                ? 'Bu chatbot zaten sepetinizde bulunuyor.'
                : 'Hata: ' . $e->getMessage();
            JsonResponse::error($msg, 409, AppConfig::ERR_DUPLICATE);
        }
    }

    /**
     * Single source of truth for what one cart line actually costs. getCart()
     * (what checkout displays) and createSubscription() (what gets charged and
     * written to param_marketplace_payments) both go through this, so the two
     * can no longer drift apart — the audit measured 216,00 TL shown against
     * 135,00 TL charged for the very same cart.
     *
     * ucret_aylik already carries the monthly discount: it is generated by
     * pricing.js deriveMonthlyPrice() as round(weekly * 4 * 0.9) at the moment
     * the seller sets a price. Applying DISCOUNT_MONTHLY_FACTOR again here
     * charged the 10% twice (effective weekly * 3.24 instead of the intended
     * weekly * 3.6), so the stored monthly price is now used as-is.
     */
    /**
     * param_marketplace_payments comes from a ParamPos-oriented schema and
     * installations differ in which of its optional columns exist. An optional
     * column is therefore written only where it is actually present — a missing
     * one must never be able to break checkout.
     */
    private static function paymentsColumnExists(Database $db, string $column): bool {
        static $cache = [];
        if (!array_key_exists($column, $cache)) {
            $row = $db->selectSingle(
                "COUNT(*) AS cnt FROM information_schema.columns
                 WHERE table_schema = DATABASE()
                   AND table_name = 'param_marketplace_payments'
                   AND column_name = ?",
                [$column]
            );
            $cache[$column] = (int) ($row['cnt'] ?? 0) > 0;
        }
        return $cache[$column];
    }

    /** PAY-004: aynı kontrolün param_marketplace_details karşılığı. */
    private static function detailsColumnExists(Database $db, string $column): bool {
        static $cache = [];
        if (!array_key_exists($column, $cache)) {
            $row = $db->selectSingle(
                "COUNT(*) AS cnt FROM information_schema.columns
                 WHERE table_schema = DATABASE()
                   AND table_name = 'param_marketplace_details'
                   AND column_name = ?",
                [$column]
            );
            $cache[$column] = (int) ($row['cnt'] ?? 0) > 0;
        }
        return $cache[$column];
    }

    private static function linePrice(float $weekly, float $monthly, int $durationWeeks): float {
        $price = $durationWeeks >= 4 ? $monthly : $weekly * $durationWeeks;
        return InputSanitizer::price($price);
    }

    public static function getCart(): void {
        $userId = AuthMiddleware::requireAuth();

        $results = Database::getInstance()->selectMulti(
            "uc.id, uc.chatbot_id, c.isim as title, c.profil_fotografi as image,
             c.ucret_haftalik as price, c.ucret_aylik as monthlyPrice,
             uc.order_weeks, ck.kategori_adi_tr as category
             FROM user_cart uc
             JOIN chatbotlar c ON uc.chatbot_id = c.id
             LEFT JOIN chatbot_kategoriler ck ON c.kategori_id = ck.id
             WHERE uc.user_id = ?",
            [$userId]
        );

        // Hand the client finished per-line and cart totals rather than letting
        // it re-derive them from the weekly price — that independent second
        // calculation is what made checkout display a number the server never
        // charged.
        $cart  = [];
        $total = 0.0;
        foreach ($results as $row) {
            $weeks = InputSanitizer::positiveInt($row['order_weeks'] ?? 0) ?: 4;
            $row['lineTotal'] = self::linePrice(
                (float) $row['price'],
                (float) $row['monthlyPrice'],
                $weeks
            );
            $total += $row['lineTotal'];
            $cart[] = $row;
        }

        JsonResponse::success([
            'cart'  => $cart,
            'total' => InputSanitizer::price($total),
        ]);
    }

    public static function getCartCount(): void {
        $userId = AuthMiddleware::requireAuth();

        $row = Database::getInstance()->selectSingle('COUNT(*) AS total FROM user_cart WHERE user_id = ?', [$userId]);
        JsonResponse::success(['count' => (int) ($row['total'] ?? 0)]);
    }

    public static function deleteCart(): void {
        require_method('POST');
        $userId = AuthMiddleware::requireAuth();
        $data   = json_decode($_POST['data'] ?? '', true) ?? [];
        $id     = InputSanitizer::positiveInt($data['id'] ?? $_POST['id'] ?? 0);
        if (!$id) JsonResponse::error('ID bulunamadı!', 400, AppConfig::ERR_VALIDATION);

        // Previously had no ownership check — anyone could remove items from
        // any user's cart by guessing the cart row id.
        Database::getInstance()->delete('user_cart', 'id = ? AND user_id = ?', [$id, $userId]);
        JsonResponse::success(['message' => 'Sepetten kaldırıldı.']);
    }

    public static function updateCart(): void {
        require_method('POST');
        $userId = AuthMiddleware::requireAuth();
        $data   = json_decode($_POST['data'] ?? '', true) ?? null;
        if (!$data || !isset($data['id'])) JsonResponse::error('Veri veya ID bulunamadı!', 400, AppConfig::ERR_VALIDATION);

        $id = InputSanitizer::positiveInt($data['id']);
        unset($data['id'], $data['user_id']);

        // SEC-014: geriye kalan her anahtar doğrudan UPDATE'e gidiyordu.
        // Sepet satırında meşru olarak değişebilecek tek şey süre; `chatbot_id`
        // istemciden yazılabilseydi kullanıcı sepete ucuz bir botu ekleyip
        // ödeme öncesi pahalısıyla değiştirebilirdi.
        [$data, $rejected] = InputSanitizer::pickAllowed($data, ['order_weeks']);
        if ($rejected !== []) {
            JsonResponse::error(
                'Bu alanlar güncellenemez: ' . implode(', ', $rejected),
                403,
                AppConfig::ERR_PERMISSION
            );
        }
        if ($data === []) JsonResponse::error('Güncellenecek alan yok.', 400, AppConfig::ERR_VALIDATION);

        $weeks = InputSanitizer::positiveInt($data['order_weeks'] ?? 0);
        if ($weeks < 1 || $weeks > 52) {
            JsonResponse::error('Süre 1-52 hafta aralığında olmalı.', 400, AppConfig::ERR_VALIDATION);
        }
        $data['order_weeks'] = $weeks;

        // Previously had no ownership check — anyone could edit any cart row by id.
        Database::getInstance()->update('user_cart', $data, 'id = ? AND user_id = ?', [$id, $userId]);
        JsonResponse::success(['message' => 'Sepet güncellendi.', 'id' => $id]);
    }

    /**
     * No frontend caller exists (the real purchase flow is createSubscription,
     * which grants time-limited access — it never transfers ownership). This
     * method used to reassign chatbotlar.owner_user_id to whoever called it
     * for any chatbot_ids, with no payment, cart, or for-sale check at all —
     * a live, session-authenticated "steal any bot for free" endpoint. There
     * being no legitimate ownership-transfer flow to preserve, the endpoint
     * is disabled outright rather than patched.
     */
    public static function buyChatbot(): void {
        JsonResponse::error('Bu işlem artık desteklenmiyor.', 410, AppConfig::ERR_VALIDATION);
    }

    /**
     * PAY-008 🟡 — idempotency anahtarı, eşzamanlılık kilidi ve rate limit
     * yoktu. Aynı sepet iki kez gönderildiğinde (çift tıklama, ağ yeniden
     * denemesi, tarayıcı yenilemesi) iki abonelik ve iki ödeme satırı
     * oluşuyordu — yani müşteri iki kez ücretlendirilirdi.
     *
     * Üç katman eklendi:
     *   1. `GET_LOCK` — aynı kullanıcının eşzamanlı checkout'ları sıraya
     *      giriyor. `withdraw()` aynı deseni zaten kullanıyor.
     *   2. Idempotency anahtarı — istemci gönderirse o kullanılıyor, yoksa
     *      sepet içeriğinden türetiliyor. Aynı anahtarla gelen ikinci istek
     *      yeni satır yazmıyor, İLK siparişin sonucunu döndürüyor.
     *   3. `checkRateLimit` — anahtarı her seferinde değiştiren bir istemci
     *      idempotency'yi atlatabilir; bu taban koruma.
     */
    public static function createSubscription(): void {
        require_method('POST');
        require_once __DIR__ . '/../../../functions/coin_engine.php';
        require_once __DIR__ . '/../../../functions/checkout_payments.php';
        $userId = AuthMiddleware::requireAuth();
        $data   = json_decode($_POST['data'] ?? '', true) ?? null;
        if (!$data || empty($data['items']) || !is_array($data['items'])) {
            JsonResponse::error('Veri bulunamadı!', 400, AppConfig::ERR_VALIDATION);
        }

        $db   = Database::getInstance();
        $conn = $db->getConnection();

        // (3) Taban : dakikada 5 checkout denemesi.
        checkRateLimit($db, 'checkout:' . $userId, 5, 60);

        // (2) Idempotency anahtarı. İstemci göndermezse sepet içeriğinden
        // türetiyoruz — böylece "aynı sepet" iki kez gönderildiğinde anahtar
        // da aynı oluyor ve ikinci istek yakalanıyor.
        $idemRaw = (string) ($data['idempotency_key'] ?? '');
        if (trim($idemRaw) === '') {
            $fingerprint = [];
            foreach ($data['items'] as $it) {
                $fingerprint[] = (int) ($it['chatbot_id'] ?? 0) . ':' . (int) ($it['duration_weeks'] ?? 0);
            }
            sort($fingerprint);
            $idemRaw = 'cart:' . implode('|', $fingerprint);
        }
        $idempotencyKey = hash('sha256', $userId . '|' . $idemRaw);

        $db->ensureTable('checkout_idempotency', 'CREATE TABLE IF NOT EXISTS checkout_idempotency (
                idem_key   CHAR(64) PRIMARY KEY,
                user_id    INT NOT NULL,
                order_id   VARCHAR(32) NULL,
                created_at DATETIME NOT NULL,
                INDEX (user_id)
            )');

        // (1) Aynı kullanıcının eşzamanlı checkout'ları sıraya girsin.
        $lockName = 'checkout_user_' . $userId;
        $lockStmt = $conn->prepare('SELECT GET_LOCK(?, 10) AS locked');
        $lockStmt->execute([$lockName]);
        if ((int) ($lockStmt->fetch()['locked'] ?? 0) !== 1) {
            JsonResponse::error('İşlem şu anda gerçekleştirilemiyor, lütfen tekrar deneyin.', 409, AppConfig::ERR_VALIDATION);
        }

        $releaseLock = static function () use ($conn, $lockName): void {
            try { $conn->prepare('SELECT RELEASE_LOCK(?)')->execute([$lockName]); } catch (Throwable $e) {}
        };

        // Kilidi aldıktan SONRA bakıyoruz: yarışı kaybeden istek burada
        // ilkinin yazdığı satırı görür.
        $existing = $db->selectSingle(
            'order_id FROM checkout_idempotency WHERE idem_key = ?',
            [$idempotencyKey]
        );
        if ($existing) {
            $releaseLock();
            JsonResponse::success([
                'message'  => 'Bu sipariş zaten oluşturulmuş.',
                'order_id' => $existing['order_id'],
                'ids'      => [],
                'repeated' => true,
            ]);
        }

        // Anahtarı ŞİMDİ rezerve ediyoruz (order_id sonra doldurulacak) —
        // böylece kilit serbest bırakıldıktan sonra gelen bir istek de
        // yakalanıyor.
        try {
            $db->execute(
                'INSERT INTO checkout_idempotency (idem_key, user_id, created_at) VALUES (?, ?, NOW())',
                [$idempotencyKey, $userId]
            );
        } catch (Throwable $e) {
            $releaseLock();
            JsonResponse::error('Bu sipariş zaten işleniyor.', 409, AppConfig::ERR_DUPLICATE);
        }

        // Bu noktadan sonraki doğrulama hataları `JsonResponse::error()` ile
        // exit ediyor — yani aşağıdaki catch bloğu ÇALIŞMIYOR ve rezervasyon
        // asılı kalıyordu. Asılı kalan rezervasyon, kullanıcının aynı sepeti
        // düzeltip tekrar göndermesini kalıcı olarak engellerdi
        // ("Bu sipariş zaten oluşturulmuş" ama ortada sipariş yok).
        //
        // Shutdown kancası, çıkış yolu ne olursa olsun tamamlanmamış
        // rezervasyonu siliyor. `$orderCompleted` başarı yolunda true olur.
        $orderCompleted = false;
        register_shutdown_function(static function () use ($db, $idempotencyKey, &$orderCompleted): void {
            if ($orderCompleted) {
                return;
            }
            try {
                $db->execute(
                    'DELETE FROM checkout_idempotency WHERE idem_key = ? AND order_id IS NULL',
                    [$idempotencyKey]
                );
            } catch (Throwable $e) {
                error_log('[checkout] asılı idempotency rezervasyonu silinemedi: ' . $e->getMessage());
            }
        });

        $subscriptionIds = [];
        $detailRows      = [];
        $itemRows        = [];
        $totalAmount     = 0.0;

        // Anchor expiry math to the DB server's clock, not PHP's — the app
        // server and DB server can run in different timezones (seen locally:
        // PHP=UTC, MySQL=UTC+3), and computing "+N days" from PHP's time()
        // then later comparing against MySQL's NOW() would skew every expiry.
        $mysqlNowRow = $db->selectSingle('NOW() AS now_time');
        $mysqlNow    = strtotime($mysqlNowRow['now_time']);

        // The loop below does several inserts/deletes per cart item with no
        // transaction — a failure partway through (e.g. item 3 of 5) used to
        // leave prior items fully purchased/removed from cart while later
        // ones silently never happened, with no way to retry cleanly.
        $conn->beginTransaction();
        try {
        foreach ($data['items'] as $item) {
            $chatbotId     = InputSanitizer::positiveInt($item['chatbot_id'] ?? 0);
            $durationWeeks = InputSanitizer::positiveInt($item['duration_weeks'] ?? 0) ?: 4;
            if (!$chatbotId) continue;

            // createSubscription is reachable directly with a hand-built items[]
            // payload, so it cannot rely on addToCart having vetted the bot —
            // every rule addToCart enforces has to be re-checked here. Skipping
            // that is how a NULL-priced independent bot bought itself: (float)
            // null === 0.0, so $price fell to 0,00, chargeCard() accepted a
            // zero amount, and the buyer still got a status=1 subscription plus
            // a "paid" payment row (observed: order ORD-2041EEC4, 0,00 TL).
            $bot = $db->selectSingle(
                "c.author_user_id, c.ucret_haftalik, c.ucret_aylik, c.is_independent,
                 pms.status AS seller_status
                 FROM chatbotlar c
                 LEFT JOIN param_marketplace_sellers pms ON pms.user_id = c.author_user_id
                 WHERE c.id = ?",
                [$chatbotId]
            );
            if (!$bot) continue;

            if ((int) $bot['is_independent'] === 1) {
                $conn->rollBack();
                JsonResponse::error('Bu chatbot pazaryerinde satışa açık değil.', 422, AppConfig::ERR_VALIDATION);
            }

            if (($bot['seller_status'] ?? '') !== 'active') {
                $conn->rollBack();
                JsonResponse::error('Bu chatbot şu anda satışa kapalı. Satıcısı henüz pazaryeri kaydını tamamlamamış.', 422, AppConfig::ERR_SELLER_INACTIVE);
            }

            $isMonthly = $durationWeeks >= 4;
            $price     = self::linePrice(
                (float) $bot['ucret_haftalik'],
                (float) $bot['ucret_aylik'],
                $durationWeeks
            );

            // An absent price is an unpriced bot, not a free one — refuse it
            // rather than recording a 0,00 TL sale.
            if ($price <= 0) {
                $conn->rollBack();
                JsonResponse::error('Bu chatbot için geçerli bir fiyat tanımlanmamış.', 422, AppConfig::ERR_VALIDATION);
            }

            $days       = $isMonthly ? AppConfig::SUBSCRIPTION_MONTHLY : $durationWeeks * AppConfig::SUBSCRIPTION_WEEKLY;
            $expiryDate = date('Y-m-d H:i:s', $mysqlNow + $days * 86400);

            $subscriptionIds[] = $db->insert('user_subscriptions', [
                'user_id'        => $userId,
                'chatbot_id'     => $chatbotId,
                'duration_weeks' => $durationWeeks,
                'expiry_date'    => $expiryDate,
                'status'         => 1,
            ]);

            $commissionRate = $isMonthly ? AppConfig::SELLER_COMMISSION_MONTHLY : AppConfig::SELLER_COMMISSION_WEEKLY;
            $detailRows[] = [
                'seller_user_id' => (int) $bot['author_user_id'],
                'chatbot_id'     => $chatbotId,
                'payable_amount' => InputSanitizer::price($price * $commissionRate),
            ];
            $itemRows[] = [
                'chatbot_id'     => $chatbotId,
                'duration_weeks' => $durationWeeks,
                'billing_period' => $isMonthly ? 'monthly' : 'weekly',
                'unit_price'     => InputSanitizer::price($isMonthly ? (float) $bot['ucret_aylik'] : (float) $bot['ucret_haftalik']),
                'line_total'     => $price,
            ];
            $totalAmount += $price;

            // Bonus message credits for this bot, advertised in the buy popup
            // (BuyModal.jsx) but previously never actually granted.
            grantPurchaseCredit($db, $userId, $chatbotId, $price, $expiryDate);

            $db->delete('user_cart', 'chatbot_id = ? AND user_id = ?', [$chatbotId, $userId]);
        }

        if (empty($subscriptionIds)) {
            $conn->rollBack();
            JsonResponse::error('Geçerli ürün bulunamadı.', 400, AppConfig::ERR_VALIDATION);
        }

        // Root-cause fix: this used to never look at $data['card'] at all —
        // any chatbot_id/duration_weeks pair succeeded with no card data
        // whatsoever. Card is validated (and, in production, actually
        // charged) only now that the real amount is known — a failure here
        // rolls back every subscription/credit/cart-delete above, so no
        // access is ever granted without a valid card.
        $card         = is_array($data['card'] ?? null) ? $data['card'] : [];
        $chargeResult = chargeCard($card, $totalAmount);
        if (!$chargeResult['success']) {
            $conn->rollBack();
            JsonResponse::error($chargeResult['message'] ?? 'Ödeme başarısız.', 402, AppConfig::ERR_PAYMENT);
        }

        // PAY-001 🔴 — sahte tahsilat gerçek ledger satırına dönüşmemeli.
        //
        // chargeCard() bir stub olduğunu 'simulated' ile bildiriyor. O
        // durumda ödeme satırı 'paid' değil, şemanın zaten varsayılan olarak
        // öngördüğü 'pending_approval' ile yazılıyor; satıcı payı da
        // 'approved' değil 'pending_approval'. Böylece:
        //   • hiçbir sahte kart çekilebilir bakiye üretemiyor (DB-003 ile
        //     birlikte: bakiye sorgusu artık p.status'u da okuyor),
        //   • şemanın iki fazlı settlement tasarımı gerçekten kullanılıyor,
        //   • gerçek entegrasyon geldiğinde tek bir bayrak değişimiyle
        //     'paid'/'approved' geri geliyor.
        $simulatedCharge = !empty($chargeResult['simulated']);
        $paymentStatus   = $simulatedCharge ? 'pending_approval' : 'paid';
        $detailStatus    = $simulatedCharge ? 'pending_approval' : 'approved';

        if ($simulatedCharge) {
            error_log(sprintf(
                '[createSubscription] SİMÜLE ödeme — ledger pending_approval yazıldı. user_id=%d amount=%s',
                $userId,
                (string) $totalAmount
            ));
        }

        // Real param_marketplace_payments columns are user_id/amount, not
        // buyer_user_id/total_amount (confirmed via live DESCRIBE) — the
        // original names here were guessed without DB access and never worked.
        $orderId    = 'ORD-' . strtoupper(InputSanitizer::randomToken(4));
        $paymentRow = [
            'order_id' => $orderId,
            'user_id'  => $userId,
            'amount'   => InputSanitizer::price($totalAmount),
            'status'   => $paymentStatus,
        ];

        // The payment row recorded a single total and nothing else, so neither
        // reconciliation nor a refund could tell what was bought or who was owed
        // what — ten columns of this table were never written at all. These
        // three are derivable from data already in hand, so record them.
        //
        // The param_* gateway columns are deliberately left untouched:
        // chargeCard() is still a stub, and writing transaction ids or a
        // net_amount would put fabricated gateway data into the ledger.
        // service_fee is left alone too — SERVICE_FEE_PERCENT exists as a
        // constant but no service fee is charged anywhere today, and filling it
        // in would imply a fee model nobody has decided on yet.
        $optionalColumns = [
            'product_amount'     => InputSanitizer::price($totalAmount),
            'items_json'         => json_encode($itemRows, JSON_UNESCAPED_UNICODE),
            'seller_splits_json' => json_encode($detailRows, JSON_UNESCAPED_UNICODE),
        ];
        foreach ($optionalColumns as $column => $value) {
            if (self::paymentsColumnExists($db, $column)) {
                $paymentRow[$column] = $value;
            }
        }

        $paymentId = $db->insert('param_marketplace_payments', $paymentRow);

        // PAY-004 🟠 — burada bir `ALTER TABLE` vardı ve ödeme transaction'ının
        // İÇİNDEYDİ. MySQL'de DDL örtük COMMIT tetikler: ALTER'a ulaşan ilk
        // checkout, o ana kadar yazılan abonelik/kredi/sepet satırlarını kalıcı
        // yapıp transaction'ı bitiriyordu; sonraki bir hata artık geri
        // alınamıyordu. Şema değişikliği migration'a taşındı
        // (database/migrations/004_add_details_chatbot_id.sql); burada yalnızca
        // sütunun VARLIĞI okunuyor, hiçbir DDL çalıştırılmıyor.
        $hasChatbotIdColumn = self::detailsColumnExists($db, 'chatbot_id');

        foreach ($detailRows as $row) {
            $detail = [
                'payment_id'        => $paymentId,
                'seller_user_id'    => $row['seller_user_id'],
                'guid_altuyeisyeri' => '', // no real ParamPos sub-merchant guid outside prod
                'gross_amount'      => $row['payable_amount'],
                'payable_amount'    => $row['payable_amount'],
                'status'            => $detailStatus,
            ];
            if ($hasChatbotIdColumn) {
                $detail['chatbot_id'] = $row['chatbot_id'];
            }
            $db->insert('param_marketplace_details', $detail);
        }

        $conn->commit();
        } catch (Exception $e) {
            if ($conn->inTransaction()) $conn->rollBack();

            // PAY-008: sipariş başarısız oldu — idempotency rezervasyonunu
            // bırak ki kullanıcı düzeltip tekrar deneyebilsin. Bırakılmazsa
            // aynı sepet kalıcı olarak "zaten oluşturulmuş" sayılırdı.
            try {
                $db->execute('DELETE FROM checkout_idempotency WHERE idem_key = ?', [$idempotencyKey]);
            } catch (Throwable $inner) {
                error_log('[checkout] idempotency rezervasyonu bırakılamadı: ' . $inner->getMessage());
            }
            $releaseLock();
            throw $e;
        }

        // Rezervasyonu gerçek sipariş numarasıyla tamamla — tekrar gönderilen
        // istek artık ilk siparişin numarasını görecek.
        try {
            $db->execute(
                'UPDATE checkout_idempotency SET order_id = ? WHERE idem_key = ?',
                [$orderId, $idempotencyKey]
            );
        } catch (Throwable $e) {
            error_log('[checkout] idempotency order_id yazılamadı: ' . $e->getMessage());
        }
        $orderCompleted = true;
        $releaseLock();

        JsonResponse::success(['message' => 'Abonelik oluşturuldu.', 'ids' => $subscriptionIds, 'order_id' => $orderId]);
    }

    public static function deleteSubscription(): void {
        require_method('POST');
        $userId = AuthMiddleware::requireAuth();
        $data   = json_decode($_POST['data'] ?? '', true) ?? [];
        $id     = InputSanitizer::positiveInt($data['id'] ?? $_POST['id'] ?? 0);
        if (!$id) JsonResponse::error('ID bulunamadı!', 400, AppConfig::ERR_VALIDATION);

        // Previously had no ownership check — anyone could cancel any user's subscription by id.
        // The ownership predicate keeps another user's row safe, but the result
        // was reported as success regardless: passing someone else's id (or a
        // nonexistent one) answered "Abonelik silindi." while nothing had been
        // deleted. Report what actually happened.
        $affected = Database::getInstance()->delete('user_subscriptions', 'id = ? AND user_id = ?', [$id, $userId]);
        if ($affected === 0) {
            JsonResponse::error('Abonelik bulunamadı.', 404, AppConfig::ERR_NOT_FOUND);
        }
        JsonResponse::success(['message' => 'Abonelik silindi.']);
    }

    public static function updateSubscription(): void {
        require_method('POST');
        $userId = AuthMiddleware::requireAuth();
        $data   = json_decode($_POST['data'] ?? '', true) ?? null;
        if (!$data || !isset($data['id'])) JsonResponse::error('Veri veya ID bulunamadı!', 400, AppConfig::ERR_VALIDATION);

        $id = InputSanitizer::positiveInt($data['id']);
        unset($data['id'], $data['user_id']);

        // SEC-002 🔴 — burası eskiden yalnızca `id` ve `user_id` alanlarını
        // çıkarıp KALANI olduğu gibi UPDATE'e veriyordu. `expiry_date`
        // istemciden yazılabildiği için kullanıcı kendi aboneliğini ücretsiz
        // olarak süresiz uzatabiliyordu; `chatbot_id` ile de ödediğinden
        // başka bir bota geçebiliyordu.
        //
        // Kullanıcının bir abonelik üzerinde meşru olarak değiştirebileceği
        // tek şey onu iptal etmek/yeniden açmaktır. Süre, bot ve fiyat
        // yalnızca sunucu tarafındaki satın alma akışında belirlenir.
        [$data, $rejected] = InputSanitizer::pickAllowed($data, ['status']);
        if ($rejected !== []) {
            JsonResponse::error(
                'Bu alanlar güncellenemez: ' . implode(', ', $rejected),
                403,
                AppConfig::ERR_VALIDATION
            );
        }
        if ($data === []) {
            JsonResponse::error('Güncellenecek alan yok.', 400, AppConfig::ERR_VALIDATION);
        }
        $data['status'] = InputSanitizer::bool($data['status']) ? 1 : 0;

        // Previously had no ownership check — anyone could edit any subscription by id.
        // As with deleteSubscription, a row that was never touched used to come
        // back as a successful update.
        $affected = Database::getInstance()->update('user_subscriptions', $data, 'id = ? AND user_id = ?', [$id, $userId]);
        if ($affected === 0) {
            // MySQL reports 0 affected rows both for "no such row" and for an
            // update that changed nothing, so confirm which one it was before
            // calling it an error.
            $exists = Database::getInstance()->selectSingle(
                'id FROM user_subscriptions WHERE id = ? AND user_id = ?',
                [$id, $userId]
            );
            if (!$exists) {
                JsonResponse::error('Abonelik bulunamadı.', 404, AppConfig::ERR_NOT_FOUND);
            }
        }
        JsonResponse::success(['message' => 'Abonelik güncellendi.', 'id' => $id]);
    }

    public static function buyProducerAccount(): void {
        require_method('POST');
        $userId = AuthMiddleware::requireAuth();
        require_once __DIR__ . '/../../../functions/ParamPosMarketplace.php';
        require_once __DIR__ . '/../../../functions/checkout_payments.php';
        require_once __DIR__ . '/../../../functions/producer_plan.php';

        $data = json_decode($_POST['data'] ?? '', true) ?? null;
        if (!$data) JsonResponse::error('Eksik veri.', 400, AppConfig::ERR_VALIDATION);

        $data['user_id'] = $userId;
        $status = buyProducerAccount(Database::getInstance(), $data);
        echo json_encode($status, JSON_UNESCAPED_UNICODE);
        exit;
    }

    public static function getProducerPlanStatus(): void {
        require_once __DIR__ . '/../../../functions/producer_plan.php';
        $userId = AuthMiddleware::requireAuth();

        $status = getProducerPlanStatus(Database::getInstance(), $userId);
        echo json_encode(array_merge(['success' => true], $status));
        exit;
    }
}
